version: 2
run:
  timeout: 5m
  allow-parallel-runners: true

issues:
  # don't skip warning about doc comments
  # don't exclude the default set of lint
  exclude-use-default: false
  # restore some of the defaults
  # (fill in the rest as needed)
  exclude-rules:
    - path: "api/*"
      linters:
        - misspell
    - path: "internal/*"
      linters:
        - dupl
        - misspell
linters:
  default-mode: standard
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unconvert
    - unparam
    - unused
    - copyloopvar
    - dupl
    - goconst
    - gocyclo
    - misspell
    - nakedret
    - prealloc
formatters:
  enable:
    - gofmt
    - goimports
