---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - s3.odit.services
  resources:
  - s3servers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - s3.odit.services
  resources:
  - s3servers/finalizers
  verbs:
  - update
- apiGroups:
  - s3.odit.services
  resources:
  - s3servers/status
  verbs:
  - get
  - patch
  - update
