---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - s3.odit.services
  resources:
  - s3buckets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - s3.odit.services
  resources:
  - s3buckets/finalizers
  verbs:
  - update
- apiGroups:
  - s3.odit.services
  resources:
  - s3buckets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - s3.odit.services
  resources:
  - s3policies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - s3.odit.services
  resources:
  - s3policies/finalizers
  verbs:
  - update
- apiGroups:
  - s3.odit.services
  resources:
  - s3policies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - s3.odit.services
  resources:
  - s3servers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - s3.odit.services
  resources:
  - s3servers/finalizers
  verbs:
  - update
- apiGroups:
  - s3.odit.services
  resources:
  - s3servers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - s3.odit.services
  resources:
  - s3users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - s3.odit.services
  resources:
  - s3users/finalizers
  verbs:
  - update
- apiGroups:
  - s3.odit.services
  resources:
  - s3users/status
  verbs:
  - get
  - patch
  - update
