# permissions for end users to edit s3servers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: s3ops
    app.kubernetes.io/managed-by: kustomize
  name: s3server-editor-role
rules:
- apiGroups:
  - s3.odit.services
  resources:
  - s3servers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - s3.odit.services
  resources:
  - s3servers/status
  verbs:
  - get
