apiVersion: s3.odit.services/v1alpha1
kind: S3Bucket
metadata:
  labels:
    app.kubernetes.io/name: s3ops
    app.kubernetes.io/managed-by: kustomize
  name: s3bucket-sample
spec:
  serverRef: 
    name: s3server-sample
    namespace: default
  region: us-east-1
