apiVersion: s3.odit.services/v1alpha1
kind: S3User
metadata:
  labels:
    app.kubernetes.io/name: s3ops
    app.kubernetes.io/managed-by: kustomize
  name: s3user-sample
spec:
  serverRef: 
    name: s3server-sample
    namespace: default
  policyRefs:
    - s3policy-sample
